### ISSUE TITLE
Centos7.6(arrch64) does not support set_attribute("qfull_time_out", self.qfull_timeout)

### ISSUE THREAD

**Issue by shibingwei-xit** [ceph/ceph-iscsi#139]
I transplant ceph to ARM node,the OS is centos 7.6(aarch64,1810),Linux kernel is 4.14.0-115.el7a.0.1.aarch64.
when I configure iscsi target, it is failure, the log message report does not find qfull_time_out attribution,may I cancel this code: new_lun.set_attribute("qfull_time_out", self.qfull_timeout) ?
thanks!

**Comment by dillaman** [comment]
Please refer to the requirements [1] -- the CentOS 7.6 kernel (kernel-3.10.0-957.el7.x86_64.rpm) or a vanilla Linux 4.16 kernel

[1] https://docs.ceph.com/docs/master/rbd/iscsi-targets/#iscsi-targets

**Comment by shibingwei-xit** [comment]
Thanks,but the centos 7.6 aarch64 kernel default is 4.14.0-115.el7a.0.1.aarch64. and I can't find the funchtion "static void tcmu_qfull_timedout(unsigned long data)"in target_core_user.c,I don't know  why they cancel this interface.

**Comment by mikechristie** [comment]
If you are going to use a longterm kernel use 4.19 based one or newer. It should have what you need.

You should not comment out code like the qfull one.

**Comment by mikechristie** [comment]
> Thanks,but the centos 7.6 aarch64 kernel default is 4.14.0-115.el7a.0.1.aarch64. and I can't find the funchtion "static void tcmu_qfull_timedout(unsigned long data)"in target_core_user.c,I don't know why they cancel this interface.

The qfull interface was added upstream in 4.16. If you run ceph-iscsi on a kernel without that file, commands are going to be retried and possible fill up the network with those retries instead of new/current commands.

So you can comment out the code if you want, but it is not supported. It will be up to you to figure out how to configure your initiator so it does not send too many commands.
