### ISSUE TITLE
I can not stop rbd-target-gw when i stoped tcmu-runner. 

### ISSUE THREAD

**Issue by swimfish09** [ceph/ceph-iscsi#41]
centos 7.6.1810
tcmu-runner 1.4.0
When i killed tcmu-runner, rbd-target-gw can not be stopped.
rbd-target-gw will hung on  method lio.drop_lun_maps(config, False).

```
[store@server1 ~]$ sudo cat /proc/73563/stack 
[<ffffffffc0426bc4>] tcmu_netlink_event+0x334/0x4a0 [target_core_user]
[<ffffffffc0427adc>] tcmu_destroy_device+0x5c/0x90 [target_core_user]
[<ffffffffc03d8334>] target_free_device+0xb4/0x120 [target_core_mod]
[<ffffffffc03d22d5>] target_core_dev_release+0x15/0x20 [target_core_mod]
[<ffffffff8e8d131a>] config_item_release+0x6a/0xf0
[<ffffffff8e8d13cc>] config_item_put+0x2c/0x30
[<ffffffff8e8cf4bb>] configfs_rmdir+0x1eb/0x310
[<ffffffff8e84e1dc>] vfs_rmdir+0xdc/0x150
[<ffffffff8e853681>] do_rmdir+0x1f1/0x220
[<ffffffff8e8548b6>] SyS_rmdir+0x16/0x20
[<ffffffff8ed74ddb>] system_call_fastpath+0x22/0x27
[<ffffffffffffffff>] 0xffffffffffffffff
```

**Comment by mikechristie** [comment]
You can't stop tcmu-runner then stop rbd-target-gw, because rbd-target-gw tries to stop and remove tcmu devices during the stop operation. There is then a bug in the kernel where it does not tell us if tcmu-runner is up/down, so we do the safe dumb thing and wait to make sure memory is not reallocated while still in user by other processes.

You need to stop tcmu-runner after rbd-target-gw.

There was fix sent for the kernel the other day:

https://marc.info/?l=target-devel&m=155138210826240&w=2

and that patch requires a kernel 4.18 or newer because it relies on another kernel fix.
